# vim:set ft=dockerfile:
FROM ubuntu:18.04

# obs !!! todo: parametrize qto-190616104728
RUN echo "root:root" | chpasswd
RUN echo 'export PS1="`date "+%F %T"` \u@\h  \w \\n\\n  "' >> /root/.bashrc
# src: https://stackoverflow.com/a/28769950/65706

# install the most basic binaries
ENV TZ=Europe/Helsinki
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 
RUN apt-get update && apt-get install -y wget curl sudo perl zip unzip gnupg2 gnupg1 git bash

WORKDIR /opt/
ADD . /opt/qto
WORKDIR /opt/qto
RUN git checkout v0.6.5
#   ^^^ todo:ysg remove 

RUN chmod 755 src/bash/qto/install/docker/provision-os-users.sh && \
    bash src/bash/qto/install/docker/provision-os-users.sh
RUN chmod 755 src/bash/qto/install/docker/install-postgres.sh && \
    bash src/bash/qto/install/docker/install-postgres.sh

# expose the PostgreSQL port
EXPOSE 15432
EXPOSE 3001

# add VOLUMEs to allow backup of config, logs and databases
# VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

# set the default command to run when starting the container
RUN chmod 755 src/bash/qto/install/docker/install-perl-modules.sh && \
    bash src/bash/qto/install/docker/install-perl-modules.sh

RUN chown -R postgres:postgres "/etc/postgresql" && \
    chown -R postgres:postgres "/var/lib/postgresql" && \
    chown -R postgres:postgres "/etc/postgresql/11/main/pg_hba.conf"

RUN rm -vr /opt/qto

USER usrqtoadmin
WORKDIR /opt/
CMD ["bash","-c","while true; do sleep 1; done;"]
