# vim:set ft=dockerfile:
FROM ubuntu:18.04

USER root
# obs !!! todo: parametrize qto-190616104728
RUN echo "root:root" | chpasswd
RUN echo 'export PS1="`date "+%F %T"` \u@\h  \w \\n\\n  "' >> /root/.bashrc
# src: https://stackoverflow.com/a/28769950/65706

# install the most basic binaries
ENV TZ=Europe/Helsinki
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get clean && apt-get update && apt-get install -y wget curl sudo perl zip unzip gnupg2 gnupg1 git bash vim

CMD ["bash","-c","while true; do sleep 1; done;"]
