# vim:set ft=dockerfile:
FROM ubuntu:18.04

ARG PRODUCT_INSTANCE_DIR
ENV PRODUCT_INSTANCE_DIR $PRODUCT_INSTANCE_DIR
ARG postgres_app_db 
ENV postgres_app_db $postgres_app_db
ARG postgres_sys_usr_admin='usrqtoadmin'
ENV postgres_sys_usr_admin_pw 'usrqtoadmin'
ARG host_host_name
ENV host_host_name $host_host_name

# obs !!! todo: parametrize qto-190616104728
RUN echo "root:root" | chpasswd
RUN echo 'export PS1="`date "+%F %T"` \u@\h  \w \\n\\n  "' >> /root/.bashrc

# install the most basic binaries
ARG TZ
ENV TZ $TZ
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 
RUN apt-get update && apt-get install -y wget curl sudo perl zip unzip gnupg2 gnupg1 git bash jq vim

WORKDIR /opt/
ADD . $PRODUCT_INSTANCE_DIR
WORKDIR $PRODUCT_INSTANCE_DIR
#   ^^^ todo:ysg replace with the git clone 

RUN chmod 755 src/bash/qto/install/docker/install-admin-utils.sh && \
    bash src/bash/qto/install/docker/install-admin-utils.sh
RUN chmod 755 src/bash/qto/install/docker/provision-os-users.sh && \
    bash src/bash/qto/install/docker/provision-os-users.sh
RUN chmod 755 src/bash/qto/install/docker/install-postgres.sh && \
    bash src/bash/qto/install/docker/install-postgres.sh

# add VOLUMEs to allow backup of config, logs and databases
# VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

# set the default command to run when starting the container
RUN chmod 755 src/bash/qto/install/docker/install-perl-modules.sh && \
   bash src/bash/qto/install/docker/install-perl-modules.sh

RUN chown -R usrqtoadmin:grpqtoadmin "/opt/csitea" && \
    chmod 777 "/opt" && \
    chmod 755 "$PRODUCT_INSTANCE_DIR/src/bash/qto/bootstrap-qto-docker.sh"


USER usrqtoadmin
WORKDIR $PRODUCT_INSTANCE_DIR
RUN $PRODUCT_INSTANCE_DIR/src/bash/qto/bootstrap-qto-docker.sh

USER root
RUN rm -vr /opt/csitea && chmod 755 "/opt"

USER usrqtoadmin
WORKDIR $PRODUCT_INSTANCE_DIR

# CMD ["bash","-c","while true; do sleep 1; done;"]
CMD bash -c $PRODUCT_INSTANCE_DIR/src/bash/qto/install/docker/docker-entry-point.sh
