#!/usr/bin/env bash

# how RATIONAL is to add code which introduces regression bugs !?
clear ; ./src/bash/qto/qto.sh -a run-unit-tests
clear ; ./src/bash/qto/qto.sh -a run-functional-tests

# scramble the secrets into random hashes
clear ; ./src/bash/qto/qto.sh -a scramble-confs
git update-index --assume-unchanged cnf/env/dev.env.json
git update-index --assume-unchanged cnf/env/tst.env.json
git update-index --assume-unchanged cnf/env/prd.env.json


# update the meta include file for each env from the dev env
for env in `echo dev tst prd` ; do cp -v met/.dev.qto met/.$env.qto ; done ;
