use strict ; use warnings ; 

use Test::Most ; 
use Test::Mojo;
use Data::Printer ; 
use FindBin;
use Mojo::UserAgent;

die_on_fail ; 

BEGIN { unshift @INC, "$FindBin::Bin/../../../../../qto/lib" }

   my $tm            = '' ; # the test message for each test 
   my $res           = {} ; 
   my $url           = {} ; 
   my $exp_err_msg   = '' ; 
   my $t             = Test::Mojo->new('Qto');
   my $appConfig     = $t->app->get('AppConfig') ; 
   my $db            = $appConfig->{ 'postgres_db_name' } ; # because each instance has it's own ...
   my $ua            = $t->ua ; # the user agent , aka http client
   my $objTimer      = {} ;

   # the HCreate back-end web action requires the following json format : 
   # the id which is BY DESIGN a requirement for ANY qto app table to work ... 
   # the content should be json format as follows

   $tm = 'id generated by the YYYYmmDDhhMMss timestamp can be used for new item creation' ; 
   $url = '/' . $db . '/hcreate/test_hcreate_table' ; 
   $objTimer          = 'Qto::App::Utils::Timer'->new( 'YYYYmmDDhhMMss' );

   my $id             = $objTimer->GetHumanReadableTime();
   ok ( $t->post_ok($url => json => {"id" =>$id})->status_is(200) , $tm );

done_testing();
