# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'



Vagrant.configure("2") do |config|

  # dev, tst and prd are separate vagrants
  config.vm.define "%ENV%-qto-vagrant" do |config|
  config.vm.hostname = "%ENV%-qto-vagrant"

  # use the latest ubuntu as a base
  config.vm.box = "generic/ubuntu1804"

  # disable updates to the configured box
  config.vm.box_check_update = false

  # dev, tst and prd could run on the same host if ip is changed ...
  # your mileage might vary ...
  config.vm.network "private_network", ip: "192.168.10.50"

  # open the the morbo dev web server ports for dev, tst and prd
  config.vm.network "forwarded_port", guest: %dev_mojo_morbo_port%, host: %dev_mojo_morbo_port%
  config.vm.network "forwarded_port", guest: %tst_mojo_morbo_port%, host: %tst_mojo_morbo_port%
  config.vm.network "forwarded_port", guest: %prd_mojo_morbo_port%, host: %prd_mojo_morbo_port%

  # open the the hypno prd web server ports for dev, tst and prd
  config.vm.network "forwarded_port", guest: %dev_mojo_hypnotoad_port%, host: %dev_mojo_hypnotoad_port%
  config.vm.network "forwarded_port", guest: %tst_mojo_hypnotoad_port%, host: %tst_mojo_hypnotoad_port%
  config.vm.network "forwarded_port", guest: %prd_mojo_hypnotoad_port%, host: %prd_mojo_hypnotoad_port%
  

  # the project dir will be visible from the vagrant @/home/vagrant/opt/qto
  config.vm.synced_folder "%product_base_dir%", "/home/vagrant/opt/"
  $script = <<-SCRIPT
         # run the bootstrap script and IMPORTANT !!! reload the bash shell
         bash /home/vagrant/opt/qto/src/bash/deployer/run.sh

         bash

         # go to the product instance dir
         cd /home/vagrant/opt
         source $(find . -name '.env') && cd qto/qto.$VERSION.$ENV.$USER

         # ensure application layer consistency, run db ddl's and load data from s3
         bash ./src/bash/qto/qto.sh -a check-perl-syntax -a scramble-confs 
         bash ./src/bash/qto/qto.sh -a provision-db-admin -a run-qto-db-ddl 
         bash ./src/bash/qto/qto.sh -a load-db-data-from-s3 -a fix-db-permissions

         # start the web server
         ./src/bash/qto/qto.sh -a mojo-hypnotoad-start
  SCRIPT

  # and run the script
  config.vm.provision "shell", inline: $script, privileged: false
  end
end
