# grab the list of cols straight from bash
export src_db='dev_qto'
export tgt_db='prd_phz'
export table_to_copy='meta_columns'
 psql -d "$src_db" -t -c \
 "SELECT column_name 
 FROM information_schema.columns 
 WHERE 1=1 
 AND table_name='"$table_to_copy"'"
 # ^^^ filter autogenerated cols if needed     

psql -h $postgres_db_host -p $postgres_db_port -d "$src_db" -c  \
 "copy ( SELECT guid, id, prio, table_name, name, description, skip_in_list, width, readonly, update_time FROM table_to_copy) TO STDOUT" |\
psql -d "$tgt_db" -c "copy $table_to_copy (guid, id, prio, table_name, name, description, skip_in_list, width, readonly, update_time) FROM STDIN"
